title: portfoilo
author: i-am-skidohbah
email: skidohbah@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  personal online portfolio

# social links
twitter_username: i_am_Skidohbah # DO NOT include the @ character, or else the build will fail!
github_username:  i-am-skidohbah # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
